### ISSUE TITLE
I think you should move the inlined CSS to a SASS file

### ISSUE THREAD

**Issue by laser** [chozandrias76/DnD-WebApp#4]
I just noticed that your JSX template uses the `style` attribute to inline some CSS rules. An example can be found [here](https://github.com/chozandrias76/DnD-WebApp/blob/master/src/main.jsx#L38). 

I think you should move this stuff into a SASS file - and reference it via a CSS.

**Comment by chozandrias76** [comment]
Tomorrow I will clean up some code and look at putting some of those styles into the sass file using the rule of thirds methodology.
